name: Build Binaries

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: uraimo/run-on-arch-action@v2.1.1
        name: Install dependencies and build Cppcheck
        id: build
        with:
          arch: armv7
          distro: ubuntu20.04
          
          # Create an artifacts directory
          setup: |
            mkdir -p "${PWD}/artifacts"
          
          # Mount the artifacts directory as /artifacts in the container
          dockerRunArgs: |
            --volume "${PWD}/artifacts:/artifacts"
      
          run: |
            apt-get update -y
            apt-get install -y python3
            python3 build.py
            #Copy built binary file to artifacts directory
            cp result/tool-cppcheck-*.tar.gz /artifacts
    
  # build-win64:
  #   runs-on: windows-latest
  #   defaults:
  #     run:
  #       shell: msys2 {0}
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: msys2/setup-msys2@v2
  #       with:
  #         msystem: MINGW64
  #         install: git mingw-w64-x86_64-toolchain mingw-w64-x86_64-libelf mingw-w64-x86_64-python-pip
  #     - name: Set up Python
  #       uses: actions/setup-python@v3
  #       with:
  #         python-version: "3.9"
  #     - name: Install PlatformIO
  #       # Used for pulling cross-platform CMake and Ninja packages
  #       run: python -m pip install platformio
  #     - name: Build
  #       run: python build.py
  #     - name: Attach artifact
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: cppcheck-win64
  #         path: result/tool-cppcheck-*.tar.gz
  #         retention-days: 1
        

  # build-lin64:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Set up Python
  #       uses: actions/setup-python@v3
  #       with:
  #         python-version: "3.9"
  #     - name: Install PlatformIO
  #       # Used for pulling cross-platform CMake and Ninja packages
  #       run: python -m pip install platformio
  #     - name: Build
  #       run: python build.py
  #     - name: Attach artifact
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: cppcheck-lin64
  #         path: result/tool-cppcheck-*.tar.gz
  #         retention-days: 1

  # build-darwin-x64:
  #   runs-on: macos-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Set up Python
  #       uses: actions/setup-python@v3
  #       with:
  #         python-version: "3.9"
  #     - name: Install PlatformIO
  #       # Used for pulling cross-platform CMake and Ninja packages
  #       run: python -m pip install platformio
  #     - name: Build
  #       env:
  #         PLATFORMIO_PACKAGE_SYSTEM_VALUES: "darwin_x86_64,darwin_arm64"
  #       run: python build.py
  #     - name: Attach artifact
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: cppcheck-darwin64
  #         path: result/tool-cppcheck-*.tar.gz
  #         retention-days: 1

  # release:
  #   runs-on: ubuntu-latest
  #   needs: [build-win64, build-lin64, build-darwin-x64]
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/download-artifact@v3
  #       with:
  #         path: final_packages
  #     - name: Display structure of downloaded files
  #       run: ls -R
  #       working-directory: final_packages
  #     - name: Release
  #       uses: softprops/action-gh-release@v1
  #       if: startsWith(github.ref, 'refs/tags/')
  #       with:
  #         files: final_packages/*/*.tar.gz
