name: Build Binaries

on: [push]

jobs:
  # build-win64:
  #   runs-on: windows-latest
  #   defaults:
  #     run:
  #       shell: msys2 {0}
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: msys2/setup-msys2@v2
  #       with:
  #         msystem: MINGW64
  #         install: git mingw-w64-x86_64-toolchain mingw-w64-x86_64-libelf mingw-w64-x86_64-python-pip
  #     - name: Set up Python
  #       uses: actions/setup-python@v3
  #       with:
  #         python-version: "3.9"
  #     - name: Install PlatformIO
  #       # Used for pulling cross-platform CMake and Ninja packages
  #       run: python -m pip install platformio
  #     - name: Build
  #       run: python build.py

    # build-lin64:
    #   runs-on: ubuntu-latest
    #   steps:
    #     - uses: actions/checkout@v2
    #     - name: Set up Python
    #       uses: actions/setup-python@v3
    #       with:
    #         python-version: "3.9"
    #     - name: Install PlatformIO
    #       # Used for pulling cross-platform CMake and Ninja packages
    #       run: python -m pip install platformio
    #     - name: Build
    #       run: python build.py

  build-armv7l:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pguyot/arm-runner-action@v2
        id: build_image
        with:
          cpu: cortex-a7
          base_image: raspios_lite:latest
          image_additional_mb: 1024
          commands: |
            sudo apt-get install -y python3 python3-pip
            echo "deb http://security.ubuntu.com/ubuntu focal-security main" | sudo tee /etc/apt/sources.list.d/focal-security.list
            sudo apt-get update && sudo apt-get install -y libssl1.1
            python3 -m pip install platformio --break-system-packages
            python3 build.py
